#!/usr/bin/env python3
# Copyright (C) 2021, Jan-Philipp Litza <jpl@plutex.de>.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.


def agent_unifi_arguments(params, hostname, ipaddress):
    return [
        elem for chunk in (
            ("-u", params["username"])
            if "username" in params else (),
            (
                "-p",
                passwordstore_get_cmdline(  # noqa: F821
                    "%s",
                    params["password"],
                ),
            )
            if "password" in params else (),
            ("--port", params["port"])
            if "port" in params else (),
            ("--no-cert-check",)
            if params.get("no-cert-check") else (),
            (hostname,),
        ) for elem in chunk
    ]


special_agent_info['unifi'] = agent_unifi_arguments  # noqa: F821
